# Generated by Django 4.2.4 on 2023-08-29 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_account_active_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='account_id',
            new_name='account',
        ),
    ]
